****Deep Leraning for NLP****
Topic : Embedding


In [3]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt


C:\Users\aishw\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


input

In [4]:
docs = ['bad',
        'badly',
        'terrible',
        'good',
        'great',
       'awesome']


Encoding 

In [5]:

# define class labels
labels = array([0,0,0,1,1,1])
# integer encode the documents
vocab_size = 6000
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)


[[1574], [2644], [3861], [4904], [4390], [3440]]


padding 

In [6]:
max_length = 350
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[1574    0    0 ...    0    0    0]
 [2644    0    0 ...    0    0    0]
 [3861    0    0 ...    0    0    0]
 [4904    0    0 ...    0    0    0]
 [4390    0    0 ...    0    0    0]
 [3440    0    0 ...    0    0    0]]


Defining Model

In [7]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=5, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 350, 8)            48000     
_________________________________________________________________
flatten_1 (Flatten)          (None, 2800)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 2801      
Total params: 50,801
Trainable params: 50,801
Non-trainable params: 0
_________________________________________________________________
None
Accuracy: 50.000000


visualization

In [ ]:
embds = model.layers[0].get_weights()[0]
print(embds.shape)
word_list = encoded_docs
print(word_list)

def plot_embedding(data, start, stop, step, fname):
  words = word_list[start:stop:step]
  x = data[start:stop:step,0]
  y = data[start:stop:step, 1]
  cm = plt.cm.get_cmap('RdYlGn')
  f = plt.figure(figsize=(8, 6))
  ax = plt.subplot(aspect='equal')
  sc = ax.scatter(x, y, lw=0, s=100, cmap=cm, alpha=1.0, marker='.', edgecolor='')
  plt.xlim(-25, 25)
  plt.ylim(-25, 25)
  ax.set_title('TSNE of Word Embeddings')
  ax.set_xlabel('TSNE 1st Dimension')
  ax.set_ylabel('TSNE 2nd Dimension')
  ax.axis('tight')

  plt.savefig(fname + '.png')
  plt.show()



tsne_embds = TSNE(n_components=2, verbose=1).fit_transform(embds)
plot_embedding(tsne_embds, 0, len(word_list), 1, "tsne_embds")

#
#conv_tsne_embds = TSNE(n_components=2).fit_transform(conv_embds)
#plot_embedding(conv_tsne_embds, 0, len(word_list), 1, "conv_tsne_embds")
#
#glove_tsne_embds = TSNE(n_components=2).fit_transform(glove_emds)
#plot_embedding(glove_tsne_embds, 0, len(word_list), 1, "glove_tsne_embds")



(6000, 8)
[[1574], [2644], [3861], [4904], [4390], [3440]]
[t-SNE] Computing 91 nearest neighbors...
[t-SNE] Indexed 6000 samples in 0.011s...
[t-SNE] Computed neighbors for 6000 samples in 7.193s...
[t-SNE] Computed conditional probabilities for sample 1000 / 6000
[t-SNE] Computed conditional probabilities for sample 2000 / 6000
[t-SNE] Computed conditional probabilities for sample 3000 / 6000
[t-SNE] Computed conditional probabilities for sample 4000 / 6000
[t-SNE] Computed conditional probabilities for sample 5000 / 6000
[t-SNE] Computed conditional probabilities for sample 6000 / 6000
[t-SNE] Mean sigma: 0.022261
[t-SNE] KL divergence after 50 iterations with early exaggeration: 92.440941
